name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue! By 
        submitting this issue, you agree to follow our [Code of Conduct](https://github.com/nmfs-ost/on-off-boarding?tab=coc-ov-file),
        which uses the NOAA Fisheries Integrated Toolbox Code of Conduct.
        
        ---

        Before filling out this report please search the existing issues to see
        if the problem has already been reported. If it has, please add a
        comment to the open issue or link to the related, but closed, issue in
        this report.
  
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: Please provide a description of the bug. Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Describe how to reproduce the bug
      description: "How can we reproduce the bug? Please be as specific as possible."
      value: |
        1. 
        2. 
        3. 
        ...
    validations:
      required: true
