name: offboard-dismap-command
on:
  repository_dispatch:
    types: [offboard-dismap-command]
jobs:
  list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            Thank you for your contributions to DisMAP! Please complete the following tasks for successfully offboarding from the project.

            ## Offboardee
              - [ ] 

            ## Project Lead
              - [ ] Remove from monthly DisMAWG meetings
              - [ ] Remove from biweekly development team meetings
              - [ ] Remove as collaborator to [DisMAP GitHub Repository](https://github.com/nmfs-ost/DisMAP)
